dbfilename redis_queue.rdb
dir /home/user1/frappe-bench/config/pids
pidfile /home/user1/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/user1/frappe-bench/config/redis_queue.acl
